### ISSUE TITLE
Separation and Convergence = 0 not working properly in 1.3 branch

### ISSUE THREAD

**Issue by DHR3D** [bo3b/3Dmigoto#97] opened 2018-06-28 23:28 UTC
I'm refixing Prey 2017 and trying to upgrade to 1.3.11 but i found the trick used in Prey to make dynamics shadows works properly don't work with 1.3.11 version and is working properly in 1.2.67. 

**d3dx.ini:
[ShaderOverride_CB_from_VS_NEW]
Hash = 3767eb5cdf830731
Separation=0
Convergence=0

Results:
1.2.67: This make ONLY shadows (that VS) become 2D, needed to later fix in PS
1.3.11: This make the entire game/render goes in 2D, separation = 1 and convergence = 0 seen in the overlay.

**Comment by masterotaku** [comment] 2018-10-05 07:37
I'm interested in a fix for this too. I had to downgrade 3Dmigoto for Tokyo Xanadu because I needed to use Separation=0 and Convergence=0 for one of the HUD shaders. And ideally I'd like to use it with Nioh too, but it isn't important enough to downgrade.

Not a super high priority problem, but for some reasons I'd like to always use the latest 3Dmigoto version (mostly for conditions in d3dx.ini).

**Comment by DarkStarSword** [comment] 2018-10-05 22:03
I'll try to look at this next week when I get back home. In the meantime can you do a quick test for me and see if it works if you do something like:

    pre x = convergence
    pre convergence = 0
    post convergence = x

**Comment by masterotaku** [comment] 2018-10-07 07:28
It works! At least partially. This is what I use:

```
pre x4 = convergence
pre separation = 0
pre convergence = 0
post convergence = x4
post separation = 100
```

It looks that the convergence thing works, I think. But the problem is that I can't save separation in a variable. I get this error in the log if I do it:

```
Syntax Error: separation
              ^: Unrecognised identifier: separation
WARNING: Unrecognised entry: pre y4 = separation
```

It happens with upper case "S" too. Using the pre and post separation works, but I have to force 100% separation for everything after that. I always use 100% separation so I have no problem with that, but other people may want to use a lower separation. What I can do (and it works) is make my own separation hotkey (with y4 variable), and then use this:

```
pre x4 = convergence
pre separation = 0
pre convergence = 0
post convergence = x4
post separation = y4
```

I just put a few possible separation values in that hotkey, but I guess can also do it as a hold hotkey with absolute value increase/decrease per frame if I want, in the "[Present]" section (like the hotkeys I made for Grandia II).

**Comment by DarkStarSword** [comment] 2018-12-24 04:41
> It looks like the convergence thing works. But the problem is that I can't save separation in a variable. I get this error in the log if I do it:

The operand is "raw_separation" to distinguish it from the pre-calculated separation value we use in the shaders (there's also "eye_separation")... I guess this was a poor choice since we used "separation" as a thing that could be set, so I'll add an alias in the next version.

**Closed** 2018-12-24 05:16 UTC
