### ISSUE TITLE
ps = "shader.hlsl" in [ShaderOverride]?

### ISSUE THREAD

**Issue by oomek** [bo3b/3Dmigoto#56] opened 2017-01-17 16:04 UTC
What do you think about allowing to define a friendly name for a shader file inside [ShaderOverride] ?
That would allow to organise the shader's folder into a logical structure with folders and friendly names. The only way to organise shaders at the moment is to use symlinks which have many disadvantages.

**Comment by DarkStarSword** [comment] 2017-01-18 01:39
I don't mind the idea, but it would add even more complexity to our replace shader routines which are already overly complicated (and I am not touching until after we have refactored these into something more manageable and squashed the bugs I know they have), and we would have to handle the additional cases in copy on mark, dumping shaders, etc... This is the sort of innocuous change that will be very difficult to add without introducing new bugs if we aren't very careful and would almost certainly come with some weird quirks in the edge cases.

This isn't ideal since it incurs extra overhead at runtime, but you could do this using a custom shader section:

    [ShaderOverrideFoo]
    hash = ...
    run = CustomShaderFoo
    handling = skip
    
    [CustomShaderFoo]
    ps = ...
    draw = from_caller

**Comment by oomek** [comment] 2017-01-18 02:53
So it comes at a cost by overcomplicating the ini :) Forced reloading would be a very desirable side effect if my shaders with includes reloaded without touching them.

**Comment by bo3b** [comment] 2017-01-18 03:27
Not to be discouraging, but I don't think this would be a good approach for 3Dmigoto.

The problem is that you are trading off a *friendly* name for the *accurate* name.  We absolutely need the hash number in order to match to shaders in-game, and obfuscating that name is problematic.  

Doing this with a friendly name, means the accurate name needs to be embedded somehow, and now you have a synchronization issue, which will lead to some situations where the wrong shader is loaded.  I don't think it really helps to trade one synchronization issue for another, when it's already possible to comment the files directly (which of course can get out of date, out of sync.)

I also am wary of adding features that would be rarely used.  Especially in a scenario like this where it adds complexity.  


For a scenario like this, I'd work out an offline technique that give you what you want.  

So for example, put all of your shaders in Git, in whatever folder layout you prefer.  You can even use friendly names, as long as you have an accurate name convention that can be found by script.

Then script a conversion/installation of the Git repo to the ShaderFixes folder, converting as desired.  You could invert the embedded accurate and friendly names, so that while you are in-game, you still have the friendly name as the first line.  

If necessary, using windows search function in the top right of explorer windows, you could search in ShaderFixes for the friendly name.

**Comment by DarkStarSword** [comment] 2017-02-20 04:42
Mind if I close this? The CustomShader method provides this even though this isn't the intended use and we don't particularly recommend it. I'm still open to other ideas to improve the workflow, but what we have now works well enough for most purposes, and there are significant challenges to any changes in this area.

**Closed by DarkStarSword** 2017-02-20 04:42 UTC
