### ISSUE TITLE
Help! How i can make a Fullbright shader?

### ISSUE THREAD

**Issue by marcocorriero** [bo3b/3Dmigoto#114] opened 2019-07-06 00:46 UTC
Im trying to make a shader that makes the entire level visible, but i dont know, neither i can find a proper shader that does the work.

**Comment by marcocorriero** [comment] 2019-07-06 04:31
i did some shader hunting, well the game doesn’t have any shadow, apparently it just relies on the existing lights.

i wish someone would help me to convert or atleast suggest what to hunt.

**Comment by DarkStarSword** [comment] 2019-07-08 09:17
"the game doesn’t have any shadow, apparently it just relies on the existing lights."
That sentence would seem to be a contradiction, since it is typically deferred lighting shaders that draw shadows, so I'm having trouble understanding what you are even after. Maybe you mean that the shadows are baked into a texture applied to each surface? In that case you might try modifying the pixel shaders responsible to ignore any baked lighting. Or maybe you mean that there is no lighting at all and each surface just has some arbitrary ambient value set? Again, modify the responsible shaders to set an ambient value of your choice.

I strongly suggest you get yourself familiar with frame analysis and use that to determine when the shadows first appear in the frame (e.g. analyse_options = dump_rt) and focus on those shaders.

Or, you might try writing a custom shader that you inject late in the frame (e.g. from the [Present] command list) that applies a brightness or gamma curve to make everything brighter in post, though the results of that would be similar to just adjusting your brightness & contrast levels (e.g. on your monitor, in the game settings or failing all that in the nvidia control panel), which I assume you would have tried well before resorting to trying to modify any shaders.


Regardless, this is not a bug in 3DMigoto and does not belong in the 3DMigoto issue tracker, so I am closing this issue. I see you have also asked for help on Discord, which along with the 3D Vision forums is a more appropriate place to ask these types of questions.

**Closed by DarkStarSword** 2019-07-08 09:17 UTC

**Comment by marcocorriero** [comment] 2019-07-09 18:17
> "the game doesn’t have any shadow, apparently it just relies on the existing lights."
> That sentence would seem to be a contradiction, since it is typically deferred lighting shaders that draw shadows, so I'm having trouble understanding what you are even after. Maybe you mean that the shadows are baked into a texture applied to each surface? In that case you might try modifying the pixel shaders responsible to ignore any baked lighting. Or maybe you mean that there is no lighting at all and each surface just has some arbitrary ambient value set? Again, modify the responsible shaders to set an ambient value of your choice.
> 
> I strongly suggest you get yourself familiar with frame analysis and use that to determine when the shadows first appear in the frame (e.g. analyse_options = dump_rt) and focus on those shaders.
> 
> Or, you might try writing a custom shader that you inject late in the frame (e.g. from the [Present] command list) that applies a brightness or gamma curve to make everything brighter in post, though the results of that would be similar to just adjusting your brightness & contrast levels (e.g. on your monitor, in the game settings or failing all that in the nvidia control panel), which I assume you would have tried well before resorting to trying to modify any shaders. It's also worth noting that while 3DMigoto can be used to inject these type of shaders it is not its primary purpose, whereas another tool ReShade is designed for this and may therefore be easier to make that work.
> 
> Regardless, this is not a bug in 3DMigoto and does not belong in the 3DMigoto issue tracker, so I am closing this issue. Feel free to continue the discussion here if you like (I should still get notifications and so on even with the issue closed) and I see you have also asked for help on Discord, which along with the 3D Vision forums is a more appropriate place to ask these types of questions.

Do you have discord? might help me with this problem.
