### ISSUE TITLE
Strange black ghosting using 3Dmigoto? 

### ISSUE THREAD

**Issue by Jimmysikisken** [bo3b/3Dmigoto#126] opened 2020-06-04 23:28 UTC
Using Helixmod and Nvidia 3D the 3d in the game is perfect:

https://i.imgur.com/RRtCtQc.jpg

But the remaster (which I have to run using 3dMigoto because there is no Helixfile yet) shows strange black shadows? (check the spherical lights).

https://i.imgur.com/oj9zYUg.jpg

How can I fix this?

Helixmod (Ghostbusters The Video Game) is standard install of the shaders on Helixmod site.

3Dmigoto  (Ghostbusters The Video Game Remastered) is a standard install of 3DMigoto 1.3.16 with Hunting=0 and Fullscreen=1.

System: Windows 10, Nvidia 425.31, Samsung Active 3D UE65JU7000, 1080Ti

**Comment by DarkStarSword** [comment] 2020-06-06 23:15
3DMigoto doesn't magically fix anything - someone (which could be you) needs to go through the hard work of creating a fix for the remaster. The original mod was by eqzitara, but he is no longer active in the modding community and there won't be much point in asking him to do it. I don't know if any of the other active modders might be ineterested in this game, but in general if you want a specific game fixed your best bet is to learn shaderhacking and do it yourself.

As always, start with Bo3b's lessons - these are for DX9/Helix Mod, but the same concepts apply to DX11/3DMigoto and you *need* to start with the basics taught here:
http://wiki.bo3b.net/index.php?title=Bo3b%27s_School_for_Shaderhackers

I'm closing this issue, since an unfixed game is not a bug in 3DMigoto and further requests for help should be directed to either the forums or discord:
https://www.mtbs3d.com/phpbb/viewforum.php?f=105
https://discord.gg/tXHYhNK

**Closed by DarkStarSword** 2020-06-06 23:15 UTC

**Comment by Jimmysikisken** [comment] 2020-06-06 23:17
Ok I will try. SO you are sure that the black shadows are shader related and I can fix them (potentially)?
