### ISSUE TITLE
32bit version broken in PCSX2

### ISSUE THREAD

**Issue by theoldsport** [bo3b/3Dmigoto#41] opened 2016-02-17 04:39 UTC
I'm not sure what could be causing this bug, or if it's just on my end, but I cannot initialize the 32bit version of 3Dmigoto in PCSX2 (on 64bit Windows 10). It does seem to load, but all functionality is broken. I failed to get it functioning on x86 versions of PCSX2 and Dolphin (emulators). The 64bit version of 3Dmigoto, however, works like a charm on Dolphin (x64).

-None of the numpad bindings have any effect, aside from numpad7 (which only slightly brightens the visuals)
-The OSD is invisible, or nonexistent
-No log is generated

A friend of mine had no issues running 32bit 3Dmigoto with PCSX2 on Windows 7, so I'm curious if someone else has any insight on this. Thank you

**Comment by bo3b** [comment] 2016-03-09 09:24
Haven't seen any serious problems with x32 version, and it's built from exact same code base, nothing special about x64 or x32 builds.  

Different games do different things though, and can introduce problems, or demonstrate flaws in 3Dmigoto.  PCSX2 might just be one of those where the wrapping is not working well.  I don't understand PCSX2 well, so this may be irrelevant, but is it DX11 only?  I see references to PS2.0 which would be DX9, and that won't be hooked or used by 3Dmigoto.  We use HelixMod for DX9 games.

If that doesn't seem to be it, make a full debug log calls=1, debug=1, unbuffered=1 in d3dx.ini, and attach it here, and we'll take a look.

**Comment by theoldsport** [comment] 2016-03-10 01:40
PCSX2 uses a plugin system to render games. There are three hardware backends, DX9, DX11, and OGL. Using the DX9 plugin and HelixMod, I was able cycle through and dump shaders without any issues. When using the DX11 plugin with 3Dmigoto, I don't seem to get any response.

I made the changes you suggested to d3dx.ini, yet the wrapper refuses to output a log.

According to a friend of mine, 3Dmigoto does work with PCSX2, however the OSD is invisible. He provided me a .zip file which includes his working build of PCSX2 with 3Dmigoto (also includes log files). Since PCSX2 is portabIe, attempted to run his build on my system, with your ini changes, and still nothing happened. 

These logs are from his working build-
[d3d11_log.txt](https://github.com/bo3b/3Dmigoto/files/166384/d3d11_log.txt)
[nvapi_log.txt](https://github.com/bo3b/3Dmigoto/files/166385/nvapi_log.txt)

Could it be that this is a hardware, Windows 10, or Nvidia driver issue on my end?

**Comment by bo3b** [comment] 2016-03-10 01:58
Since he gets a log, and it's a fairly recent version of 3Dmigoto, that suggests that yours is probably installed in the wrong directory.  If you don't get a log at all, that means that the wrapper was not called, and not installed.

The d3d11.dll and nvapi.dll files need to be right next to the .exe that runs, not next to the plugin.  Most likely.  When the exe runs it will look for d3d11.dll and if it finds us, we'll get installed. (maybe vice versa of course, lots of possibilities)

I can't explain the no-hud.  If the hud doesn't work, I'd expect hunting keys to fail as well.  Might be part of the plugin architecture that changes things though.

**Comment by theoldsport** [comment] 2016-03-10 02:02
I thought it might be installed wrong too, but it isn't. Both .dlls are installed in the same directory as the .exe. I wouldn't have thought to put it anywhere else since I've used 3Dmigoto in numerous other programs without issues

**Comment by bo3b** [comment] 2016-03-10 02:08
Experiment with different directories then, as the lack of log file demonstrates it's not being loaded.  Or perhaps ask your friend what directory he is using.

**Comment by theoldsport** [comment] 2016-03-10 02:27
I linked his exact setup here, completely untouched-
[pcsx2-v1.5.0-dev-345-g44e6445-windows-x86_masterotaku(no-bios_no-memcards).zip](https://github.com/bo3b/3Dmigoto/files/166394/pcsx2-v1.5.0-dev-345-g44e6445-windows-x86_masterotaku.no-bios_no-memcards.zip)

This build works fine for him, but doesn't load the wrapper on my system. I installed the .dlls in exactly the same manner, and made sure the ini was configured correctly. It simply isn't loading, without any discernible reason why.

**Comment by masterotaku** [comment] 2017-09-09 06:49
@DarkStarSword and @bo3b are already aware that I have this problem too on Windows 10 (no matter the settings or 3Dmigoto build used, it doesn't hook), but I'm commenting to receive updates, in case there are some news.

As an opposite example, the Helixmod dll loads correctly with GSdx in DX9 mode.

The 3D status of hundreds of games is at stake, so I hope this can be solved someday.

**Comment by bo3b** [comment] 2017-10-20 00:51
Looked into this one a bit with masterotaku's help.  

Problem is that pcxs2 does some sort of special loading technique for DX11, which locks out _any_ d3d11.dll injector or override.  Reshade dx11 has the same problem.  The reason it works on Win7 is because they have a special 8.1OrGreaters check in their code.  Presumably 8.0 works, 8.1 fails.

Reshade and HelixMod load when using the dx9 variant, because there is no special loader code for the dx9 path, normal LoadLibrary rules are in effect.

This is not a bug in 3Dmigoto, and there is nothing we can change to make this work.

**Comment by mirh** [comment] 2017-10-20 10:17
Ohh, wait, maybe I know what's the deal here. 
Try the thing to this commit https://github.com/PCSX2/pcsx2/tree/f1b3d7d036b01375b9ed59f84eecadaa95a8f9fc

**Comment by mirh** [comment] 2017-10-21 16:36
Wait a minute, there was no 8.1OrGreater check anywhere in the code on February 2016 when this issue was reported. 
And the only point where loadlibrary is called is [here](https://github.com/PCSX2/pcsx2/blob/96c921c776c2362b61f09f7935ffefff725c0fe3/plugins/GSdx/GSUtil.cpp#L325). Nothing special seems to happen.

**Comment by bo3b** [comment] 2017-10-22 13:41
I don't think that first commit has anything to do with this problem, it seems like it is changing config files of some form.

For the second one, I agree that should work, the loadlibrary is on the local d3d11.dll, which would be 3Dmigoto if it's in the right working directory.  However, they do have an OS check there, it's just not done using 8.1OrGreater call.  Doesn't look like it matters for the loadlibrary, but if they do that check there it can be happening elsewhere.

If there is some way to log what pcxs2 is doing, that would help clarify why this doesn't work.

**Comment by mirh** [comment] 2017-10-22 13:45
> I don't think that first commit has anything to do with this problem, it seems like it is changing config files of some form.

The first commit was meant to be the first one before [this](https://github.com/PCSX2/pcsx2/pull/1238). 
That added a real 8.1OrGreater check, and I was thinking to that, but it's impossible for it to be the cause of this issue. 

> Doesn't look like it matters for the loadlibrary, but if they do that check there it can be happening elsewhere.

AFAIK.. That's really only just to print OS version in the logs.

**Comment by masterotaku** [comment] 2017-10-26 06:25
I made a PCSX2 github issue: https://github.com/PCSX2/pcsx2/issues/2106

Someone said "VorpX's VR DX11 wrapper works perfectly fine in both software and hardware renderers. I would take a look at your program again and see how the wrapper is interfacing".

I have tried very old PCSX2 builds, the oldest one from 2012-07-24, and 3Dmigoto didn't work. I'm not sure if those code paths for W8.1 or higher are the problem.

**Comment by DarkStarSword** [comment] 2017-10-26 13:24
I'm pretty sure VorpX uses a completely different method to hook get into the game than we do, so "VorpX works" doesn't necessarily mean that it's 3DMigoto's fault, but I'd need to look at this to be sure. For now I'm re-opening this - that doesn't mean I'm admitting that this is a 3DMigoto bug, but I'm re-opening it because I *hate* when two projects blame each other and both refuse to fix a problem, so I want this issue open *somewhere*.

**Comment by mirh** [comment] 2018-01-10 15:39
So.. Highest-in-charge windows dev said there's nothing special in our LoadLibraryEx (I mean, aside of what I linked 2 comments above I guess... but that seemingly came later than this issue). 

Can anybody check a Windows 8 system with Secure Boot? I [heard](http://steamcommunity.com/groups/SpecialK_Mods/discussions/0/1319962514590954694/#c1621724915811631110) it may cause problems
(protip: VMware workstation 14 supports it too)

**Comment by bo3b** [comment] 2018-01-10 17:19
> I'm pretty sure VorpX uses a completely different method to hook into the game than we do, so "VorpX works" doesn't necessarily mean that it's 3DMigoto's fault, but I'd need to look at this to be sure. For now I'm re-opening this - that doesn't mean I'm admitting that this is a 3DMigoto bug, but I'm re-opening it because I hate when two projects blame each other and both refuse to fix a problem, so I want this issue open somewhere.

Based on what I've learned in the last month or so, it's entirely possible that our wrapping scheme has been causing problems here.  I've been working out the new approach, with the goal of improved compatibility.  Once this is released in a month or so, it will be worth trying it against this problem.

**Comment by bo3b** [comment] 2018-02-02 14:16
Don't think this will make a difference for this problem, but we now have a new version of our code that works much better with Win10 and is compatible with Steam overlay.  We are using a different technique to hook into DXGI, and thus this new version is worth a try here.  This new version has so far worked on every game that we previously had problems with.

https://github.com/bo3b/3Dmigoto/releases/tag/1.3.1

**Comment by DarkStarSword** [comment] 2018-04-30 07:49
Based on the progress and workaround in the pcsx2 issue tracker this is a pcsx2 issue and so there is nothing else we can really do on this side, so closing this issue. If that changes, feel free to reopen this.

**Closed by DarkStarSword** 2018-04-30 07:49 UTC
